/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.altendis.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Form service. Represents a row in the &quot;Altendis_Form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.altendis.contact.model.impl.FormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.altendis.contact.model.impl.FormImpl}.
 * </p>
 *
 * @author pif
 * @see Form
 * @see com.altendis.contact.model.impl.FormImpl
 * @see com.altendis.contact.model.impl.FormModelImpl
 * @generated
 */
public interface FormModel extends BaseModel<Form> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form model instance should use the {@link Form} interface instead.
	 */

	/**
	 * Returns the primary key of this form.
	 *
	 * @return the primary key of this form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form.
	 *
	 * @param primaryKey the primary key of this form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form ID of this form.
	 *
	 * @return the form ID of this form
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this form.
	 *
	 * @param formId the form ID of this form
	 */
	public void setFormId(long formId);

	/**
	 * Returns the group ID of this form.
	 *
	 * @return the group ID of this form
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this form.
	 *
	 * @param groupId the group ID of this form
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this form.
	 *
	 * @return the create date of this form
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this form.
	 *
	 * @param createDate the create date of this form
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the nom of this form.
	 *
	 * @return the nom of this form
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this form.
	 *
	 * @param nom the nom of this form
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this form.
	 *
	 * @return the prenom of this form
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this form.
	 *
	 * @param prenom the prenom of this form
	 */
	public void setPrenom(String prenom);

	/**
	 * Returns the telephone of this form.
	 *
	 * @return the telephone of this form
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this form.
	 *
	 * @param telephone the telephone of this form
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the email of this form.
	 *
	 * @return the email of this form
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this form.
	 *
	 * @param email the email of this form
	 */
	public void setEmail(String email);

	/**
	 * Returns the comment of this form.
	 *
	 * @return the comment of this form
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this form.
	 *
	 * @param comment the comment of this form
	 */
	public void setComment(String comment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Form form);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Form> toCacheModel();

	@Override
	public Form toEscapedModel();

	@Override
	public Form toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}